### ISSUE TITLE
Consider always having white on bottom

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL23/solver-halloqueensgambit#14]
https://github.com/TU-CSCI2322-FL23/solver-halloqueensgambit/blob/dd660c62db0b89a8cfd977e0d313edb7fc65f208/chess.hs#L81-L82

While this is very pretty, it will make debugging using prettyShow harder, and that is the primary use of prettyShow.

**Comment by LeviBetsy** [comment]
Did it
