### ISSUE TITLE
Consider making a "isValidMove" to make this more efficient

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL23/solver-halloqueensgambit#19]
https://github.com/TU-CSCI2322-FL23/solver-halloqueensgambit/blob/dd660c62db0b89a8cfd977e0d313edb7fc65f208/moves.hs#L129C3-L129C62

Or hte evil version: makeUnsafeMove

**Comment by LeviBetsy** [comment]
Created makeUnsafeMove function
